apiVersion: v1
whatsapp:
  baseUrl: "https://graph.facebook.com/v19.0"
  phoneNumberId: "${WHATSAPP_PHONE_NUMBER_ID}"
  accessToken: "${WHATSAPP_API_TOKEN}"
  webhookVerifyToken: "${WHATSAPP_WEBHOOK_VERIFY_TOKEN}"
  messageTemplates:
    phoneVerification:
      name: "hello_world"
      language: "en"
      components:
        - type: "body"
          parameters:
            - type: "text"
              text: "{{verification_code}}"
    phoneVerificationIt:
      name: "hello_world"
      language: "it"
      components:
        - type: "body"
          parameters:
            - type: "text"
              text: "{{verification_code}}"
